package com.fitconnect.backend.dto;

import lombok.AllArgsConstructor;
import lombok.Data;

/**
 * One AI-recommended coach: the full {@link CoachProfileResponse} (so the frontend has all the coach
 * details it already knows how to render) plus a short {@code reason} generated by Gemini explaining
 * why this coach fits the user's profile. Returned by
 * {@code GET /api/users/{userId}/coaches/recommended} in Gemini's ranking order.
 *
 * <p>This is an ADD-ON view: it wraps the existing {@code CoachProfileResponse} rather than replacing
 * it, so the non-AI coach endpoints are unaffected.
 */
@Data
@AllArgsConstructor
public class CoachRecommendationResponse {
    private CoachProfileResponse coach;
    private String reason;
}
