package com.fitconnect.backend.dto;

import lombok.AllArgsConstructor;
import lombok.Data;

/**
 * One AI-recommended community group: the full {@link CommunityGroupResponse} (with its
 * {@code memberCount} / {@code isJoined} computed for the current user, exactly like the non-AI list
 * endpoint) plus a short {@code reason} generated by Gemini. Returned by
 * {@code GET /api/users/{userId}/community-groups/recommended} in Gemini's ranking order.
 *
 * <p>This is an ADD-ON view: it wraps the existing {@code CommunityGroupResponse} rather than
 * replacing it, so the non-AI community-group endpoints are unaffected.
 */
@Data
@AllArgsConstructor
public class CommunityGroupRecommendationResponse {
    private CommunityGroupResponse group;
    private String reason;
}
